version: '3'
networks:
  api:
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-api
    ports:
      - "8082:80"
    volumes:
      - /Applications/MAMP/htdocs/booking-engine-api-code-1:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
      - mongo
    networks:
      - api

  mysql:
    image: mysql:5.7.22
    container_name: mysql-server-api
    tty: true
    ports:
      - "4307:3306"
    volumes: 
      - ./data/mysql:/var/lib/mysql
    environment: 
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAG: dev
      SERVICE_NAME: mysql
    networks:
      - api

  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php-api
    volumes: 
      - /Applications/MAMP/htdocs/booking-engine-api-code-1:/var/www/html
      - ./php-ini/php.ini:/usr/local/etc/php/conf.d/api-custom.ini
    networks:
      - api